services:
  franka_ros2:
    build:
      context: .
      dockerfile: Dockerfile-cpu
      network: host
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    image: franka_ros2_cpu
    container_name: franka_ros2_cpu
    network_mode: "host" # Use host network mode for ROS 2 communication
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ./:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./limits.conf:/etc/security/limits.conf
      - /dev:/dev
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      # NVIDIA_VISIBLE_DEVICES: all # Use all available GPUs
      # NVIDIA_DRIVER_CAPABILITIES: all # Use all driver capabilities
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    # runtime: nvidia # Use NVIDIA runtime for GPU support
